import type { Product } from "./types/product";

import img1 from "../../assets/zapatillas/MB-04-phoenix.webp";
import img2 from "../../assets/zapatillas/zapatilla-puma-2.webp";
import img3 from "../../assets/zapatillas/zapatilla-puma-3.webp";
import img4 from "../../assets/zapatillas/zapatilla-puma-4.webp";
import img5 from "../../assets/zapatillas/zapatillas-puma.webp";

export const ALL_PRODUCTS: Product[] = [
	// OFERTAS (10)
	{
		id: "1",
		name: "Nike Elevate Pro Oferta",
		price: 149999,
		category: "ofertas",
		brand: "Nike",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img1,
	},
	{
		id: "2",
		name: "Nike Court Drive Low",
		price: 139999,
		category: "ofertas",
		brand: "Nike",
		sizes: ["38", "39", "40", "41"],
		recommendedFor: "hombre",
		imageUrl: img2,
	},
	{
		id: "3",
		name: "Nike Bounce Street",
		price: 159999,
		category: "ofertas",
		brand: "Nike",
		sizes: ["40", "41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img3,
	},
	{
		id: "4",
		name: "Adidas Pro Bounce Oferta",
		price: 149999,
		category: "ofertas",
		brand: "Adidas",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img4,
	},
	{
		id: "5",
		name: "Adidas Streetball Low",
		price: 139999,
		category: "ofertas",
		brand: "Adidas",
		sizes: ["38", "39", "40"],
		recommendedFor: "mujer",
		imageUrl: img5,
	},
	{
		id: "6",
		name: "Adidas Triple Threat",
		price: 159999,
		category: "ofertas",
		brand: "Adidas",
		sizes: ["41", "42", "43", "44"],
		recommendedFor: "unisex",
		imageUrl: img1,
	},
	{
		id: "7",
		name: "Puma Court Rider Oferta",
		price: 144999,
		category: "ofertas",
		brand: "Puma",
		sizes: ["39", "40", "41"],
		recommendedFor: "unisex",
		imageUrl: img2,
	},
	{
		id: "8",
		name: "Puma RS Bounce",
		price: 134999,
		category: "ofertas",
		brand: "Puma",
		sizes: ["38", "39", "40"],
		recommendedFor: "mujer",
		imageUrl: img3,
	},
	{
		id: "9",
		name: "Puma Skyline Mid",
		price: 154999,
		category: "ofertas",
		brand: "Puma",
		sizes: ["40", "41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img4,
	},
	{
		id: "10",
		name: "Puma City Dunk",
		price: 149999,
		category: "ofertas",
		brand: "Puma",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img5,
	},

	// DEPORTE (10)
	{
		id: "11",
		name: "Nike Game Time Pro",
		price: 259999,
		category: "deporte",
		brand: "Nike",
		sizes: ["41", "42", "43", "44"],
		recommendedFor: "hombre",
		imageUrl: img1,
	},
	{
		id: "12",
		name: "Nike Air Court Elite",
		price: 269999,
		category: "deporte",
		brand: "Nike",
		sizes: ["42", "43", "44", "45"],
		recommendedFor: "unisex",
		imageUrl: img2,
	},
	{
		id: "13",
		name: "Nike Fastbreak React",
		price: 249999,
		category: "deporte",
		brand: "Nike",
		sizes: ["40", "41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img3,
	},
	{
		id: "14",
		name: "Adidas Court Control",
		price: 239999,
		category: "deporte",
		brand: "Adidas",
		sizes: ["40", "41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img4,
	},
	{
		id: "15",
		name: "Adidas Elevate Mid",
		price: 229999,
		category: "deporte",
		brand: "Adidas",
		sizes: ["39", "40", "41"],
		recommendedFor: "mujer",
		imageUrl: img5,
	},
	{
		id: "16",
		name: "Adidas Bounce Arena",
		price: 259999,
		category: "deporte",
		brand: "Adidas",
		sizes: ["42", "43", "44", "45"],
		recommendedFor: "hombre",
		imageUrl: img1,
	},
	{
		id: "17",
		name: "Puma Skyline Pro",
		price: 249999,
		category: "deporte",
		brand: "Puma",
		sizes: ["41", "42", "43", "44"],
		recommendedFor: "unisex",
		imageUrl: img2,
	},
	{
		id: "18",
		name: "Puma Fast Court",
		price: 239999,
		category: "deporte",
		brand: "Puma",
		sizes: ["40", "41", "42"],
		recommendedFor: "mujer",
		imageUrl: img3,
	},
	{
		id: "19",
		name: "Puma Triple Double",
		price: 269999,
		category: "deporte",
		brand: "Puma",
		sizes: ["42", "43", "44", "45"],
		recommendedFor: "hombre",
		imageUrl: img4,
	},
	{
		id: "20",
		name: "Puma Court Impact",
		price: 259999,
		category: "deporte",
		brand: "Puma",
		sizes: ["41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img5,
	},

	// MODA (10)
	{
		id: "21",
		name: "Nike Streetball Icon",
		price: 219999,
		category: "moda",
		brand: "Nike",
		sizes: ["39", "40", "41", "42", "43"],
		recommendedFor: "unisex",
		imageUrl: img1,
	},
	{
		id: "22",
		name: "Nike Urban Dunk Low",
		price: 209999,
		category: "moda",
		brand: "Nike",
		sizes: ["38", "39", "40", "41"],
		recommendedFor: "mujer",
		imageUrl: img2,
	},
	{
		id: "23",
		name: "Nike Barrio Court",
		price: 229999,
		category: "moda",
		brand: "Nike",
		sizes: ["41", "42", "43", "44"],
		recommendedFor: "hombre",
		imageUrl: img3,
	},
	{
		id: "24",
		name: "Adidas Triple Stripe",
		price: 219999,
		category: "moda",
		brand: "Adidas",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img4,
	},
	{
		id: "25",
		name: "Adidas Barrio Style",
		price: 209999,
		category: "moda",
		brand: "Adidas",
		sizes: ["38", "39", "40"],
		recommendedFor: "mujer",
		imageUrl: img5,
	},
	{
		id: "26",
		name: "Adidas Court Lifestyle",
		price: 229999,
		category: "moda",
		brand: "Adidas",
		sizes: ["41", "42", "43", "44"],
		recommendedFor: "unisex",
		imageUrl: img1,
	},
	{
		id: "27",
		name: "Puma City Court",
		price: 219999,
		category: "moda",
		brand: "Puma",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img2,
	},
	{
		id: "28",
		name: "Puma Street Glow",
		price: 209999,
		category: "moda",
		brand: "Puma",
		sizes: ["38", "39", "40"],
		recommendedFor: "mujer",
		imageUrl: img3,
	},
	{
		id: "29",
		name: "Puma Retro Court",
		price: 229999,
		category: "moda",
		brand: "Puma",
		sizes: ["41", "42", "43", "44", "45"],
		recommendedFor: "hombre",
		imageUrl: img4,
	},
	{
		id: "30",
		name: "Puma Urban Skyline",
		price: 219999,
		category: "moda",
		brand: "Puma",
		sizes: ["39", "40", "41", "42"],
		recommendedFor: "unisex",
		imageUrl: img5,
	},
];
